=== KMenant/TP-SIO-2/SLAM4/XML/Cours XML/article.dtd
<?xml version="1.0"?>
<!ELEMENT Article (Titre, Texte)>
	<!ELEMENT Titre (#PCDATA)>
	<!ELEMENT Texte (Paragraphe+)>
		<!ELEMENT Paragraphe (Mot, Reference)>
			<!ELEMENT Mot (#PCDATA)>
			<!ELEMENT Reference (Web?, Ouvrage?)>
				<!ELEMENT Web (Nom, Url)>
					<!ELEMENT Nom (#PCDATA)>
					<!ELEMENT Url (#PCDATA)>
				<!ELEMENT Ouvrage (Titre, Date, Editeur, Auteur)>
					<!ELEMENT Titre (#PCDATA)>
					<!ELEMENT Date (#PCDATA)>
					<!ELEMENT Editeur (#PCDATA)>
					<!ELEMENT Auteur (#PCDATA)>

=== KMenant/TP-SIO-2/SLAM4/XML/Cours XML/fichier.xml
<?xml version="1.0"?>
<!DOCTYPE article SYSTEM "article.dtd">
<Article>
	<Titre>Que boy acer</Titre>
	<Texte>
		<Paragraphe>
			<Mot></Mot>
			<Reference>
				<Web>
					<Nom></Nom>
					<Url></Url>
				</Web>
				<Ouvrage>
					<Titre></Titre>
					<Date></Date>
					<Editeur></Editeur>
					<Auteur></Auteur>
				</Ouvrage>
			</Reference>
		</Paragraphe>
	</Texte>
</Article>
